apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: rbac-dashboard
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "dashboard"
        effect: "NoSchedule"
      nodeSelector:
        kubernetes.io/hostname: worker1
      containers:
        - name: frontend
          image: ghcr.io/abir-287/kuberbac-frontend:ec82997a741282cd1d05d0e97d5b48c655d0ca07
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
      imagePullSecrets:
        - name: ghcr-secret
