apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: rbac-dashboard
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: backend-sa
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "dashboard"
        effect: "NoSchedule"
      nodeSelector:
        kubernetes.io/hostname: worker1
      containers:
        - name: backend
          image: ghcr.io/abir-287/kuberbac-backend:29aeb308c94c9c00e00b4f41bdc49616774e3745
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: backend-config
          env:
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: SESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: SESS_SECRET
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: GITHUB_TOKEN
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      imagePullSecrets:
        - name: ghcr-secret
