apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: rbac-dashboard
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "R00t$tr0ngP@ss"
  MYSQL_DATABASE: "db_penggajian3"
  MYSQL_USER: "cluster_admin"
  MYSQL_PASSWORD: "your_strong_password"
