apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: abir-ben-nasr-view-binding
  namespace: abir
subjects:
  - kind: User
    name: ben.nasr.abir287@gmail.com
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: abir-ben-nasr-edit-binding
  namespace: argocd
subjects:
  - kind: User
    name: ben.nasr.abir287@gmail.com
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-cluster-admin-binding
  namespace: rbac-dashboard
subjects:
  - kind: User
    name: admin
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-admin-binding
  namespace: developer-ns
subjects:
  - kind: User
    name: admin
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: rbac-dashboard
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backend-sa-admin-binding
subjects:
  - kind: ServiceAccount
    name: backend-sa
    namespace: rbac-dashboard
roleRef:
  kind: ClusterRole
  name: cluster-admin   # Full permissions to manage RBAC as requested
  apiGroup: rbac.authorization.k8s.io
